package ru.TelegramBot.BotLogic;

public enum NavigationBotStates {
    HOME,
    CATALOG,
    BASKET,
    MAIN_SETTINGS,
    USERNAME_SETTINGS,
    USERADDRESS_SETTINGS,
    USERPHONE_SETTINGS,
    HELP,
    ABOUT,
    ORDERS,
    DELIVERY_PROBLEM,
    PIPES,
    BEER,
    DELIVERYLOCATION,
    DELIVERYUSERNAME,
    DELIVERYUSERPHONE,
    DELIVERYCONFIRM,
    ADDINGPRODUCTAMOUNT
}
